# NumPy

0. [NumPy manual](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [1]:
import numpy as np

## Generating array

In [2]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Inspect array

In [4]:
a.shape, a.ndim, a.size

((3, 5), 2, 15)

In [5]:
a.itemsize, a.dtype

(8, dtype('int64'))

## Special arrays

In [6]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [8]:
np.empty((4,5))

array([[  6.91294400e-310,   2.50664482e-316,   6.91291527e-310,
          6.91291527e-310,   6.91291527e-310],
       [  6.91291527e-310,   6.91291527e-310,   6.91291527e-310,
          6.91291527e-310,   6.91291527e-310],
       [  6.91291527e-310,   6.91291527e-310,   6.91291527e-310,
          6.91291527e-310,   6.91291527e-310],
       [  6.91291527e-310,   6.91291527e-310,   6.91291527e-310,
          2.50602032e-316,   6.91294145e-310]])

In [9]:
np.random.random((2,3))

array([[ 0.66815737,  0.27485223,  0.89501386],
       [ 0.30723698,  0.62791822,  0.12906746]])

In [10]:
# 9 numbers from 0 to 2
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [11]:
x = np.linspace( 0, 2*np.pi, 100 )
np.sin(x)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

## Basic Operations


In [12]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [13]:
a - b, a + b, a * b

(array([ 9, 18, 27, 36, 45]),
 array([11, 22, 33, 44, 55]),
 array([ 10,  40,  90, 160, 250]))

In [14]:
a + 2, a * 2, a ** 2

(array([12, 22, 32, 42, 52]),
 array([ 20,  40,  60,  80, 100]),
 array([ 100,  400,  900, 1600, 2500]))

### Filter

In [15]:
a < 30

array([ True,  True, False, False, False], dtype=bool)

In [16]:
a[a < 30]

array([10, 20])

### Product

In [17]:
np.dot(a, b), (a * b).sum()

(550, 550)

In [18]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 100, 10).reshape(3, 3)

In [19]:
a * b

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [20]:
# matrix product
np.dot(a, b)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

### Array methods

In [21]:
a.sum(), a.min(), a.max()

(45, 1, 9)

In [22]:
a.any(), a.all()

(True, True)

In [25]:
a.sum(axis=0), a.sum(axis=1)

(array([12, 15, 18]), array([ 6, 15, 24]))